name: CI/CD Workflow
on:
  push:
    branches:
      - main
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Lista directorio
        run: tree .
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Testeo
        run: pytest
      - name: Lint
        run: ruff check .

  docker-image:
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Login en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/back-calculadora:latest .
      - name: Push
        run: docker push ${{ secrets.DOCKER_USER }}/back-calculadora:latest

  build-and-push-github-package:
    runs-on: ubuntu-latest
    needs: docker-image
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Login en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.hagarbo }}
          password: ${{ secrets.GIT_ACTIONS_TOKEN }}
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.hagarbo }}/back-calculadora:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.hagarbo }}/back-calculadora:latest
