name: publish-workflow

on: [push]

jobs:
  test:
      runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
          - name: Install the code linting and formatting tool Ruff
        run: pipx install ruff
          - name: Lint code with Ruff
            run: ruff check --output-format=github --target-version=py39
          - name: Check code formatting with Ruff
            run: ruff format --diff --target-version=py39
            continue-on-error: true


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
    run: docker build . --file Dockerfile --tag adrianomanzano/back-calculadora:v1
